# Métodos para la Resolución de Sistemas de Ecuaciones

Resolver un sistema de ecuaciones consiste en  encontrar los valores $x_1, x_2, ..., x_n$ que en forma simultánea satisfacen un sistema de ecuaciones:

\begin{array}{lcl}
f_1(x_1, x_2, ..., x_n)  & = & 0\\
f_2x_1, x_2, ..., x_n)  & = & 0\\
 & \vdots & \\
f_n(x_1, x_2, ..., x_n)  & = & 0\\
\end{array}

En este laboratorio resolveremos sistemas de ecuaciones lineales y no lineales.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ivan-jgr/computacion-cientifica/blob/main/Laboratorios/Laboratorio-8.ipynb)

## Sistemas de Ecuaciones Lineales

Un sistema de ecuaciones lineal se puede representar de forma general como:


\begin{array}{lcl}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n  & = & b_1\\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n  & = & b_2\\
 & \vdots & \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n  & = & b_n\\
\end{array}

donde $a_{mn}$ son coeficientes constantes y $b_n$ son los terminos independientes constantes. Es común emplear la siguiente notación matricial para describir estos sistemas de ecuaciones:
$$\mathbf{A} \mathbf{x} = \mathbf{b},$$

donde $\mathbf{A} = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots && \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}, \quad \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix} \quad \text{y} \quad \mathbf{b} = \begin{bmatrix}b_1 \\b_2 \\ \vdots \\b_n \end{bmatrix}$.


### Método de Gauss-Jacobi

La matriz $A$ puede descomponerse en una matriz diagonal $D$, una matrix triangular inferior $L$ y una matriz triangular superior $U$:

$$A=D+L+U$$

$$\text{donde} \qquad D = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & a_{nn} \end{bmatrix} \text{ y } L+U = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ a_{21} & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & 0 \end{bmatrix}$$

La solución es obtenida de forma iterativa:

$$ \mathbf{x}^{(k+1)} = D^{-1} (\mathbf{b} - (L+U) \mathbf{x}^{(k)})$$

#### <ins> Problema 1 </ins>

Implementar el método de Jacobi en la función `jacobi`. Los métodos `np.diag`, `np.diagflat` y `np.dot` pueden serle útiles.

In [22]:
import numpy as np

# Ejemplo de una matrix
A = np.array([[2.0,1.0],[5.0,7.0]])
# el método np.diag permite obtener los elementos en la diagonal principal de un matriz
np.diag(A)

array([2., 7.])

In [25]:
D = np.diag(A)
# el método np.diagflat permite construir una matrix de nxn especificando su diagonal
np.diagflat(D)

array([[2., 0.],
       [0., 7.]])

In [26]:
# np.dot le permite multiplicar dos matrices
b = b = np.array([11.0,13.0])

np.dot(A, b)

array([ 35., 146.])

In [27]:
# también puede multiplicar dos matrices usando @
A@b

array([ 35., 146.])

In [1]:
def jacobi(A, b, x0, max_iters):
    """
    Parámetros:
    -----------
    A: Matriz de coeficientes, asuma que es un numpy array de nxn
    b: Matriz de terminos independientes, asuma que es un numpy array de nx1
    x0: estimación inicial, asuma que es un numpy array de nx1
    max_iter: máximo número de interaciones
    """

Ahora usemos su implementación para resolver el siguiente sistema de ecuaciones:

\begin{array}{lcl}
10x_1 + 2x_2 – x_3 &=& 27 \\
–3x_1 – 6x_2 + 2x_3 &=& –61.5 \\
x_1 + x_2 + 5x_3 &=&  –21.5 \\
\end{array}

In [41]:
# Definimos la matrice de coeficientes
A = np.array([[10.0, 2.0, -1.0],[-3.0, -6.0, 2.0], [1.0, 1.0, 5.0]])
# Matriz de terminos independientes
b = np.array([27.0, -61-5, -21.5])
# Estimación inicial de la solución
x0 = np.array([1.0,1.0, 1.0])
# Numero máximo de iteraciones
max_iter = 30

sol = jacobi(A, b, x0, max_iter)

print(f"A =  {A}\n\n b = {b}")

print(f"\nSolución aproximada: {sol}")

A =  [[10.  2. -1.]
 [-3. -6.  2.]
 [ 1.  1.  5.]]

 b = [ 27.  -66.  -21.5]

Solución aproximada: [ 0.32871972  8.79411765 -6.12456747]


In [44]:
# Verifiquemos que la aproximación
np.isclose(A@sol - b, np.zeros(3))

array([ True,  True,  True])

### Método de Gauss-Seidel

El método de Seidel es muy similar al de Jacobi, pero en este método la matriz $A$ se descompone de la siguiente forma:
$$A = L_* + U,$$

$$\text{donde} \qquad L_* = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ a_{21} & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix} \text{ y } U = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ 0 & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & 0 \end{bmatrix}$$

La solución es obtenida de forma iterativa:
$$\mathbf{x}^{(k+1)} = L_*^{-1} \left(\mathbf{b} - U \mathbf{x}^{(k)}\right)$$

#### <ins> Problema 2 </ins>

Implementar el método de Gauss-Seidel en la función `seidel`.

In [3]:
def seidel(A, b, x0, max_iters):
    """
    Parámetros:
    -----------
    A: Matriz de coeficientes, asuma que es un numpy array de nxn
    b: Matriz de terminos independientes, asuma que es un numpy array de nx1
    x0: estimación inicial, asuma que es un numpy array de nx1
    max_iter: máximo número de interaciones
    """

Resolvamos el mismo sistema de ecuaciiones que en el problema anterior.

In [49]:
# Definimos la matrice de coeficientes
A = np.array([[10.0, 2.0, -1.0],[-3.0, -6.0, 2.0], [1.0, 1.0, 5.0]])
# Matriz de terminos independientes
b = np.array([27.0, -61-5, -21.5])
# Estimación inicial de la solución
x0 = np.array([1.0,1.0, 1.0])
# Numero máximo de iteraciones
max_iter = 30

sol = seidel(A, b, x0, max_iter)

print(f"A =  {A}\n\n b = {b}")

print(f"\nSolución aproximada: {sol}")

A =  [[10.  2. -1.]
 [-3. -6.  2.]
 [ 1.  1.  5.]]

 b = [ 27.  -66.  -21.5]

Solución aproximada: [ 0.32871972  8.79411765 -6.12456747]


## Sistemas de Ecuaciones No Lineales

Decimos que un sistema de ecuaciones es no-lineal cuando al menos una de las ecuaciones del sistema es no lineal. El método del punto fijo y el de Newton-Raphson puede extenderse para este tipo de sistemas.

El método de Newton-Raphson para sistemas de ecuaciones no lineales puede deducirse en forma similar al método para una variable, usando la expansion en serie de Taylor multivariable obtenemos la fórmula de Newton-Raphson multivariable:

$$\mathbf{x}^{(k+1)} = \mathbf{x}^{(k)} - \mathbf{J}(\mathbf{x}^{(k)})^{-1} \mathbf{f}(\mathbf{x}^{(k)},$$

donde $\mathbf{J}$ es la matriz jacobiana:

$$\mathbf{J} = \begin{bmatrix}
    \cfrac{\partial f_1}{\partial x_1} & \cdots & \cfrac{\partial f_1}{\partial x_n} \\
    \vdots & \ddots & \vdots \\
    \cfrac{\partial f_m}{\partial x_1} & \cdots & \cfrac{\partial f_m}{\partial x_n} 
\end{bmatrix}$$

Calcular $\mathbf{J}^{-1}$ puede ser problematico en muchos casos, por lo que existe un método conocido como Newton–Krylov que emplea otro método para calcular el jacobiano inverso.

`scipy` posee una implementación del método de Newton-Krylov en el paquete `optimize` llamado `newton_krylov`. Usemos este método para resolver el siguiente sistema de ecuaciones:

$$
\begin{array}{lcl}
u + 0.5v &=& 1 \\
-0.5u^2 + 0.5v^2 &=& 0
\end{array}$$

In [50]:
# Note que defimos la función de tal forma que recive un arreglo
def fun(x):
    return [x[0] + 0.5 * x[1] - 1.0,

            0.5 * (x[1] - x[0]) ** 2]

In [51]:
from scipy import optimize

x0 = np.array([0., 0.])
sol = optimize.newton_krylov(fun, x0, verbose=True)

sol

0:  |F(x)| = 0.5; step 1
1:  |F(x)| = 0.125; step 1
2:  |F(x)| = 0.03125; step 1
3:  |F(x)| = 0.0078125; step 1
4:  |F(x)| = 0.00195313; step 1
5:  |F(x)| = 0.000488282; step 1
6:  |F(x)| = 0.00012207; step 1
7:  |F(x)| = 3.05177e-05; step 1
8:  |F(x)| = 7.62943e-06; step 1
9:  |F(x)| = 1.90737e-06; step 1


array([0.66731771, 0.66536458])

#### <ins> Problema 3 </ins>

Determine las raíce de las siguientes ecuaciones no lineales utilizando el método de Newton-Krylov:

\begin{array}{lcl}
y &=& -x^2 + x + 0.75\\
x^2 &=& y + 5xy
\end{array}

Utilíce como estimaciones iniciales $x = y = 1.2$.

In [ ]:
# Resuelva aquí el problema 3

<hr>

# **Instrucciones Generales**
1. Este laboratorio será realizado de manera *individual*.
2. **Fecha de entrega**: Lunes 01 de Noviembre de 2021. Su solución debe subirla en un archivo ZIP enviado por GES y debe contener el archivo .ipynb con sus respuesta a cada inciso solicitado en cada uno de los *Problemas* indicados en la parte superior.